# Generated by Django 3.1.4 on 2020-12-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconsults', '0002_preconsult_checklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preconsult',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preconsult',
            name='recommendation',
            field=models.TextField(max_length=500),
        ),
    ]
