# Generated by Django 3.1.4 on 2020-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconsults', '0003_auto_20201217_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconsult',
            name='height',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preconsult',
            name='weight',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
