# Generated by Django 3.1.4 on 2021-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconsults', '0004_auto_20201219_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconsult',
            name='check_abdominoplasty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preconsult',
            name='check_liposculpture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preconsult',
            name='check_mastopexy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preconsult',
            name='check_nymphoplasty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preconsult',
            name='check_otoplasty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preconsult',
            name='check_prosthesis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preconsult',
            name='check_rinoplasty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preconsult',
            name='date_operate',
            field=models.CharField(default=0.047619047619047616, max_length=100),
            preserve_default=False,
        ),
    ]
