# Generated by Django 3.1.4 on 2021-06-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconsults', '0005_auto_20210606_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconsult',
            name='check_lifting',
            field=models.BooleanField(default=False),
        ),
    ]
