# Generated by Django 3.1.4 on 2021-06-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconsults', '0006_preconsult_check_lifting'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconsult',
            name='type_rinoplasty',
            field=models.CharField(default='Anterior', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preconsult',
            name='date_operate',
            field=models.CharField(max_length=10),
        ),
    ]
